# .github/workflows/lancers_scraper.yml
name: Lancers Scraper with Excel

on:
  schedule:
    - cron: '0 */23 * * *'  # 23時間ごと
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps
          
      - name: Pull latest data
        run: |
          git pull origin main
          
      - name: Run scraper
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: python fetch_lancers_improved.py
        
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add 案件情報.xlsx *.json
          git diff --staged --quiet || (git commit -m "Update: $(date +'%Y-%m-%d %H:%M') JST" && git push)