name: Lancers Scraper with Excel

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: xlsx-append
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Pull latest
        run: |
          git config pull.rebase true
          git pull origin main

      - name: Run scraper (append to 案件情報.xlsx)
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          EXCEL_PATH: 案件情報.xlsx
        run: python fetch_lancers_improved.py

      - name: Commit and push with retry
        run: |
          set -e
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "案件情報.xlsx" *.json || true
          for i in 1 2 3 4 5; do
            git diff --staged --quiet && { echo "No changes"; exit 0; }
            git commit -m "Append: $(date +'%Y-%m-%d %H:%M') JST" || true
            git push && exit 0
            echo "Push failed. rebasing..."
            git pull --rebase origin main || true
            sleep 5
          done
          echo "Push failed after retries" >&2
          exit 1
